% function  mat_to_matlab(varargin)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%mat 格式转换为画图
global PathName
if PathName~=0
    cd(PathName);
    [FileName,PathName,~] = uigetfile([PathName,'\\*.*']); % 读取雷达数据
else
    [FileName,PathName,~] = uigetfile('*.*'); % 读取雷达数据
end
if FileName==0
    return;
end
data=importdata([PathName,'\\',FileName]);
len=length(data);
POS0.header='#BESTPOSA';
VEL0.header='#BESTVELA';
i_pos=1;
i_vel=1;
for i=1:len
    j=1;
    header='';
    while(data{i}(j)~=',')
        header(j)=data{i}(j);
        j=j+1;           
    end
    j=j+1;
   if (strcmp(header,POS0.header))
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.Week{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.Week(i_pos)=str2double(temp.Week{i_pos});            
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.Seconds{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.Seconds(i_pos)=str2double(temp.Seconds{i_pos});             
            j=j+1;
            while(data{i}(j)~=';')            
                j=j+1;
            end
            j=j+1;
            k=1;
            while(data{i}(j)~=',')
                POS.sol_stat{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
            end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                POS.pos_sype{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.lat{i_pos}(k)=data{i}(j);                
                j=j+1;
                k=k+1;
             end 
            POS.lat(i_pos)=str2double(temp.lat{i_pos}); 
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.lon{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            POS.lon(i_pos)=str2double(temp.lon{i_pos}); 
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.hgt{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.hgt(i_pos)=str2double(temp.hgt{i_pos});              
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.undulation{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            POS.undulation(i_pos)=str2double(temp.undulation{i_pos});               
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                POS.datum_id{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end             
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.lat_dev{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.lat_dev(i_pos)=str2double(temp.lat_dev{i_pos});               
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.lon_dev{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end  
            POS.lon_dev(i_pos)=str2double(temp.lon_dev{i_pos});              
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.hgt_dev{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.hgt_dev(i_pos)=str2double(temp.hgt_dev{i_pos}); 
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.SVs{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.SVs(i_pos)=str2double(temp.SVs{i_pos}); 
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.solnSVs{i_pos}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            POS.solnSVs(i_pos)=str2double(temp.solnSVs{i_pos}); 
            j=j+1;            
           i_pos=i_pos+1;
    
   elseif (strcmp(header,VEL0.header))
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            while(data{i}(j)~=',')
                j=j+1;
            end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.Week{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            VEL.Week(i_vel)=str2double(temp.Week{i_vel});            
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.Seconds{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            VEL.Seconds(i_vel)=str2double(temp.Seconds{i_vel});             
            j=j+1;
            while(data{i}(j)~=';')            
                j=j+1;
            end
            j=j+1;
            k=1;
            while(data{i}(j)~=',')
                VEL.sol_stat{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
            end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                VEL.pos_sype{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.latency{i_vel}(k)=data{i}(j);                
                j=j+1;
                k=k+1;
             end 
            VEL.latency(i_vel)=str2double(temp.latency{i_vel}); 
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.age{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            VEL.age(i_vel)=str2double(temp.age{i_vel}); 
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.V{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            VEL.V(i_vel)=str2double(temp.V{i_vel});              
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.cog{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end
            VEL.cog(i_vel)=str2double(temp.cog{i_vel});               
            j=j+1;
            k=1;
             while(data{i}(j)~=',')
                temp.Vz{i_vel}(k)=data{i}(j);
                j=j+1;
                k=k+1;
             end 
            VEL.Vz(i_vel)=str2double(temp.Vz{i_vel});               
            j=j+1;                  
           i_vel=i_vel+1;
   end   
   
end
lenv=length(VEL.Seconds);
lenp=length(POS.Seconds);
len=min(lenv,lenp);

isv=find(VEL.Week~=0,1);
isp=find(VEL.Week~=0,1);
is=max(isv,isv);
VN=VEL.V(is:len)'.*cosd(VEL.cog(is:len)');
VE=VEL.V(is:len)'.*sind(VEL.cog(is:len)');
% is=1;
data_ck=[POS.Seconds(is:len)'-POS.Seconds(is)'+18+4+1+0.8,POS.lat(is:len)',POS.lon(is:len)',POS.hgt(is:len)',POS.lat_dev(is:len)',POS.lon_dev(is:len)',POS.hgt_dev(is:len)',POS.SVs(is:len)',POS.solnSVs(is:len)',VEL.V(is:len)',VEL.cog(is:len)',-VEL.Vz(is:len)',VN,VE];
fid=fopen([PathName,'\\',FileName(1:end-6),'gps718d.dat'],'w');
fprintf(fid,'t lat lon hgt lat_dev lon_dev hgt_dev SVs solnSVs V cog VD VN VE\n');
    [count,num]=size(data_ck);
    for i=1:count
        for j=1:num
            fprintf(fid,'%f ',data_ck(i,j));
        end
        fprintf(fid,'\n');
    end
    fclose(fid);



